package com.movies.movies_challenge.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name="Movies")
public class Movie {

    // The title of the model
    @Id
    private String title;
    // The launch date
    private String date;
    // Rating (0 to 10)
    private Integer rank;
    // The revenue generated by the model
    private Integer revenue;

    public Movie() {
    }

    public Movie(String title, String date, Integer rank, Integer revenue) {
        this.title = title;
        this.date = date;
        this.rank = rank;
        this.revenue = revenue;
    }

    public Movie(Movie movie) {
        this.title = movie.getTitle();
        this.date = movie.getDate();
        this.rank = movie.getRank();
        this.revenue = movie.getRevenue();
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Integer getRank() {
        return rank;
    }

    public void setRank(Integer rank) {
        this.rank = rank;
    }

    public Integer getRevenue() {
        return revenue;
    }

    public void setRevenue(Integer revenue) {
        this.revenue = revenue;
    }

    @Override
    public String toString() {
        return "Movie{" +
                "title='" + title + '\'' +
                ", date='" + date + '\'' +
                ", rank=" + rank +
                ", revenue=" + revenue +
                '}';
    }
}
